# specify here default training configuration
defaults:
  - _self_
  - dataset: dataset.yaml
  - model: cpd_params.yaml

# path to original working directory
original_work_dir: ${hydra:runtime.cwd}

# path to output directory
save_dir: ${hydra:runtime.output_dir}/saves/

# disable python warnings if they annoy you
ignore_warnings: True

# seed for random number generators in pytorch, numpy and python.random
seed: 123

# default name for the experiment, determines logging folder path
name: ${dataset.distribution}_${dataset.seq_len}_${dataset.d}_${dataset.p}_${dataset.k}_seed_${seed}